service:
  user: cat
  workspace_root: /home/cat/Workspace/task_ws
  setup_paths:
    - /home/cat/Workspace/driver_ws/install/setup.bash
    - /home/cat/Workspace/task_ws/install/setup.bash
  environment:
    RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    CYCLONEDDS_URI: file:///home/cat/Config/cyclonedds_large_message.xml
    ROS_DOMAIN_ID: "26"
  ros_distro: jazzy
  ros_log_dir: /home/cat/inspection_logs
  install_dir: /opt/inspection_bringup
  restart: on-failure
  restart_sec: 5
  timeout_stop_sec: 30
  sudo_default_password: cat

navigation:
  service_name: inspection-navigation.service
  enabled_on_boot: true
  systemd:
    nice: -10
    cpu_weight: 900
    io_weight: 900
    oom_score_adjust: -900
  launch_args:
    navigate_config_path: /home/cat/Workspace/task_ws/src/inspection_bringup/config/navigate.yaml

inspection_system:
  service_name: inspection-system.service
  enabled_on_boot: true
  launch_args:
    system_config_path: /home/cat/Workspace/task_ws/src/inspection_bringup/config/system.yaml
